useSidebarSearch: true
legacySearch: false
showVersion: true
primaryColor: '#B10000'
trianglifyOptions:
  x_colors: ['#000', '#B10000', '#000']
extraCss:
  - 'assets/css/asciidoc-admonitionblock.scss'
social:
  twitter: 'holisticon'
  github: 'holunda-io/camunda-bpm-data'
  other:
    - link: 'https://www.holunda.io/camunda-bpm-data/'
      label: 'Home'
      icon: 'fas fa-home'
metaComponents:
  - type: 'orchidSearch'
menu:
  - type: 'page'
    title: 'Quick Start'
    itemId: 'Quick Start'

  - type: 'submenu'
    title: 'User Guide'
    menu:
      - type: 'wiki'
        section: 'user-guide'
      - type: 'page'
        title: 'Changelog'
        itemId: 'Changelog'

  - type: 'submenu'
    title: 'Developer Guide'
    menu:
      - type: 'wiki'
        section: 'developer-guide'
      - type: 'page'
        title: 'Readme'
        itemId: 'Readme'
      - type: 'page'
        title: 'License'
        itemId: 'License'

  - type: 'sourcedocPages'
    submenuTitle: 'JavaDoc All Packages'
    moduleType: 'javadoc'
    node: 'packages'
    asSubmenu: true
